### ISSUE TITLE
hello there im getting this error

### ISSUE THREAD

**Issue by harsha-99** [KoStard/PDF-cover-extractor#1]

**Comment by harsha-99** [comment]
Traceback (most recent call last):
  File "pdf2image.py", line 1, in <module>
    from pdf2image import convert_from_bytes
  File "C:\Users\SRIHARSHA\Anaconda3\pdf2image.py", line 1, in <module>
    from pdf2image import convert_from_bytes
ImportError: cannot import name 'convert_from_bytes'

**Comment by KoStard** [comment]
Did you install the pdf2image, then maybe you have to update that? - But you have to know, that this isn't working on the windows, because of pdfinfo, which is only for unix OSs.
